<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mall</groupId>
        <artifactId>mall-system</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>mall-web</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-product</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-order</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-member</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-marketing</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-finance</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-search</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
